# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2214bb7fd04a387a77c0ab6eb90aa0751027c3b8cb6ea62cd03df66631ec1afc6b167cffe3fca3143e91112c5d0f6e1fc4ed9955271891c712c391501d315551

test:
  secret_key_base: 041dfc1c3794fd4cf6564ff27d3ce28cbca3a7b2ed346130f9353165fb5c1ef7e2082dacac428b665d80cbfd9020db75be1237059a06499937536f109758e76f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
